
name: FinalProjeOdev C1

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 Corretto
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file FinalProjeOdev/pom.xml
      - name: Coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/FinalProjeOdev/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
